[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Marcus Oliveira", email = "marcus.oliveira2403@gmail.com"},
]
dependencies = [
    "django>=4.2",
    "djangorestframework>=3.14.0",
]
requires-python = ">=3.10"
license = {text = "Marcus Oliveira"}
